on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
jobs:
  manualjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!!!!"
